const SCREEN_WIDTH = 900;
const SCREEN_HEIGHT = 700;
const SCREEN_CENTER_X = SCREEN_WIDTH/2;
const SCREEN_CENTER_Y = SCREEN_HEIGHT/2;

const DIST_TO_RESET_ASTEROID = 1000;

const AST_VEL_MAG_MIN = 1;
const AST_VEL_MAG_MAX = 4;


const ASTEROID_COUNT = 4;
